=== AgID/suap-gt-specifiche/to_moduli/02_entities/ent_persona_v1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    
    xmlns:epers="http://agid.it/suap/entities/persona"
    
    xmlns:vpergen="http://agid.it/suap/vocabularies/persona_genere"
    xmlns:ccodelist="http://agid.it/suap/commons/codelist"      
    xmlns:canncl="http://agid.it/suap/commons/xsdAnnotations" 
    xmlns:ctipi="http://agid.it/suap/commons/tipi"
    
    targetNamespace="http://agid.it/suap/entities/persona"
    elementFormDefault="qualified" attributeFormDefault="qualified"    
    version="1.0.0" xml:lang="it">
      
    <xsd:import namespace="http://agid.it/suap/commons/xsdAnnotations" schemaLocation="../commons-xsd-annotations.xsd"/>    
    <xsd:import namespace="http://agid.it/suap/commons/codelist" schemaLocation="../commons-codelist.xsd"/>
    <xsd:import namespace="http://agid.it/suap/commons/tipi" schemaLocation="../commons-tipi.xsd"/> 
    <xsd:import namespace="http://agid.it/suap/vocabularies/persona_genere" schemaLocation="../01_vocabularies/voc_persona_genere_v1.0.0.xsd"/>
    
    <xsd:complexType name="persona_ctype">
        <xsd:sequence>
            <xsd:element name="codice_fiscale" type="ctipi:codice_fiscale_stype" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="nome" type="ctipi:stringa_standard_stype" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="cognome" type="ctipi:stringa_standard_stype" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="sesso" type="vpergen:sesso_voc" minOccurs="0" maxOccurs="1"/>            
            <xsd:element name="data_nascita" type="xsd:date" minOccurs="0" maxOccurs="1"/>
            <xsd:choice minOccurs="0" maxOccurs="1">
                <xsd:element name="luogo_nascita_italiano" type="ccodelist:CodeType" minOccurs="1" maxOccurs="1" >
                    <xsd:annotation>
                        <xsd:appinfo>                        
                            <canncl:codeListReference>
                                <canncl:ShortName>IT:SUAP:CL:ComuniItalianiStorico</canncl:ShortName>
                            </canncl:codeListReference>                        
                        </xsd:appinfo>                    
                    </xsd:annotation>                    
                </xsd:element>                                   
                <xsd:element name="stato_estero" type="ccodelist:CodeType" minOccurs="1" maxOccurs="1" >
                    <xsd:annotation>
                        <xsd:appinfo>                        
                            <canncl:codeListReference>
                                <canncl:ShortName>IT:SUAP:CL:Stati</canncl:ShortName>
                            </canncl:codeListReference>                        
                        </xsd:appinfo>                    
                    </xsd:annotation>
                </xsd:element>                    
            </xsd:choice>
       </xsd:sequence>        
    </xsd:complexType>          
    
    <xsd:element name="persona" type="epers:persona_ctype"/>    
</xsd:schema>

=== AgID/suap-gt-specifiche/to_moduli/old/test_cases_FVG_entities/persona/ent_persona_v1.0.0.tc.ok.estero.xml
<?xml version="1.0" encoding="UTF-8"?>
<ep:persona xmlns:vpg="http://agid.it/suap/vocabularies/persona_genere"
 xmlns:ep="http://agid.it/suap/entities/persona"
 xmlns:cl="http://agid.it/suap/commons/codelist"
 xmlns:ca="http://agid.it/suap/commons/xsdAnnotations"
 xmlns:ct="http://agid.it/suap/commons/tipi"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://agid.it/suap/entities/persona ../../ent_persona_v1.0.0.xsd">
    <ep:codice_fiscale>AAAAAA00A00A000A</ep:codice_fiscale>
    <ep:nome>nome0</ep:nome>
    <ep:cognome>cognome0</ep:cognome>
    <ep:sesso>maschio</ep:sesso>
    <ep:data_nascita>2006-05-04</ep:data_nascita>
    <ep:luogo_nascita_estero>luogo_nascita_estero0</ep:luogo_nascita_estero>
    <ep:stato_estero>SL</ep:stato_estero>
</ep:persona>

=== AgID/suap-gt-specifiche/to_moduli/moduli_fvg/02_entita/test_cases/ent_persona_v1.0.0.tc.ok.italiano - Copy.xml
<?xml version="1.0" encoding="UTF-8"?>
<ep:persona xmlns:vpg="http://vocabolari/persona_genere"
 xmlns:ep="http://entita/persona"
 xmlns:cl="http://agid.it/suap/commons/codelist"
 xmlns:ca="http://agid.it/suap/commons/xsdAnnotations"
 xmlns:ct="http://agid.it/suap/commons/tipi"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://entita/persona file:/F:/softwareDEV/GIT/repos/suap-gt-specifiche/to_moduli/moduli_fvg/02_entita/ent_persona_v1.0.0.xsd">
    <ep:codice_fiscale>AAAAAA00A00A000A</ep:codice_fiscale>
    <ep:nome>nome0</ep:nome>
    <ep:cognome>cognome0</ep:cognome>
    <ep:sesso>maschio</ep:sesso>
    <ep:data_nascita>2006-05-04</ep:data_nascita>
<!--    <ep:luogo_nascita_italiano cl:codeListID_cl="codeListID_cl0" cl:name_cl="name_cl0" cl:versionID_cl="versionID_cl0">luogo_nascita_italiano0</ep:luogo_nascita_italiano>-->
    <ep:luogo_nascita_estero>luogo_nascita_estero0</ep:luogo_nascita_estero>
    <ep:stato_estero cl:codeListID_cl="codeListID_cl1" cl:name_cl="name_cl1" cl:versionID_cl="versionID_cl1">stato_estero0</ep:stato_estero>
</ep:persona>
